name: Test&Lint&Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.2'

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec

    - name: Run rubocop
      run: bundle exec rubocop
  
  deploy:
    # needs: test_lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Deploy EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
        
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            # Load .bashrc or .bash_profile
            source ~/.bashrc || source ~/.bash_profile
            rbenv rehash
            # Check rbenv status and bundle command location
            echo "rbenv version: $(rbenv version)"
            echo "bundle location: $(which bundle)"
            cd /home/***/RealWorld &&
            # Fetch latest repository and restart RealWorld
            git fetch --all &&
            git reset --hard origin/main &&
            bundle install &&
            sudo systemctl restart myapp
          '



            
